blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
]

post/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from . import views

app_name = 'post'
urlpatterns = [
  path('', views.index, name='index'),
  path('post/<int:post_id>/', views.post, name='post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
from django.db import models

class Topic(models.Model):
  text = models.CharField(max_length=100)

  def __str__(self):
    return self.text


class Post(models.Model):
  topic = models.ForeignKey(Topic, on_delete=models.PROTECT)
  text = models.TextField()
  date = models.DateTimeField(auto_now_add=True)

  class Meta:
    verbose_name_plural = 'posts'

  def __str__(self):
    return f'{self.text[:50]}...'

post/views.py
from django.shortcuts import render

from .models import Post

def index(request):
  posts = Post.objects.order_by('-date')
  context = {'posts': posts}
  print(context)
  return render(request, 'post/index.html', context)


def post(request, post_id):
  post = Post.objects.get(id=post_id)
  context = {'post': post}
  return render(request, 'post/post.html', context)

post/templates/post/base.html
{% block content %}{% endblock content %}

post/templates/post/index.html
{% extends "post/base.html" %}

{% block content %}
  <ul>
    {% for post in posts %}
      <li>
        <a href="{% url 'post:post' post.id %}">{{ post }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet</li>
    {% endfor %}
  </ul>
{% endblock content %}

post/templates/post/post.html
{% extends "post/base.html" %}

{% block content %}
  <div>{{ post }}</div>
{% endblock content %}